import type { OGTemplate } from '@/lib/types'

export const SEED_TEMPLATES: Omit<OGTemplate, 'id' | 'created_at'>[] = [
  {
    name: 'Blog Post',
    slug: 'blog-post',
    category: 'blog',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 1,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #0f172a 0%, #1e1b4b 50%, #0f172a 100%)' },
      { type: 'shape', shape: 'rect', x: 0, y: 0, width: 8, height: 630, color: '#06b6d4', opacity: 1 },
      { type: 'text', key: 'title', label: 'Title', default_value: 'Your Blog Post Title', x: 80, y: 180, font_size: 56, font_weight: '700', color: '#ffffff', max_width: 900 },
      { type: 'text', key: 'description', label: 'Description', default_value: 'A brief description of your blog post that grabs attention.', x: 80, y: 320, font_size: 24, font_weight: '400', color: '#94a3b8', max_width: 900 },
      { type: 'text', key: 'author', label: 'Author', default_value: 'by Author Name', x: 80, y: 520, font_size: 20, font_weight: '500', color: '#06b6d4' },
      { type: 'text', key: 'site', label: 'Website', default_value: 'yoursite.com', x: 1000, y: 520, font_size: 18, font_weight: '400', color: '#64748b' },
    ],
  },
  {
    name: 'Product Launch',
    slug: 'product-launch',
    category: 'product',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 2,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #0c0a1a 0%, #1a0533 50%, #06071b 100%)' },
      { type: 'shape', shape: 'circle', x: 900, y: 100, width: 400, height: 400, color: '#8b5cf6', opacity: 0.15, border_radius: 200 },
      { type: 'shape', shape: 'circle', x: 100, y: 400, width: 300, height: 300, color: '#06b6d4', opacity: 0.1, border_radius: 150 },
      { type: 'text', key: 'badge', label: 'Badge', default_value: 'NEW RELEASE', x: 80, y: 120, font_size: 16, font_weight: '600', color: '#06b6d4' },
      { type: 'text', key: 'title', label: 'Product Name', default_value: 'Introducing Your Product', x: 80, y: 200, font_size: 60, font_weight: '800', color: '#ffffff', max_width: 800 },
      { type: 'text', key: 'tagline', label: 'Tagline', default_value: 'The next generation of amazing things.', x: 80, y: 360, font_size: 28, font_weight: '400', color: '#a78bfa' },
      { type: 'text', key: 'cta', label: 'CTA', default_value: 'Try it free →', x: 80, y: 480, font_size: 22, font_weight: '600', color: '#06b6d4' },
    ],
  },
  {
    name: 'Event Announcement',
    slug: 'event-announcement',
    category: 'event',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 3,
    layers: [
      { type: 'background', gradient: 'linear-gradient(180deg, #0a0a0a 0%, #171717 100%)' },
      { type: 'shape', shape: 'rect', x: 0, y: 580, width: 1200, height: 50, color: '#06b6d4', opacity: 1 },
      { type: 'text', key: 'date', label: 'Date', default_value: 'MARCH 15, 2026', x: 80, y: 100, font_size: 18, font_weight: '600', color: '#06b6d4' },
      { type: 'text', key: 'title', label: 'Event Name', default_value: 'The Annual Conference', x: 80, y: 180, font_size: 64, font_weight: '800', color: '#ffffff', max_width: 1040 },
      { type: 'text', key: 'location', label: 'Location', default_value: 'San Francisco, CA', x: 80, y: 380, font_size: 24, font_weight: '400', color: '#a1a1aa' },
      { type: 'text', key: 'tagline', label: 'Tagline', default_value: 'Join 5,000+ developers for 3 days of talks, workshops & more.', x: 80, y: 440, font_size: 22, font_weight: '400', color: '#71717a' },
    ],
  },
  {
    name: 'Tutorial / Guide',
    slug: 'tutorial-guide',
    category: 'tutorial',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 4,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #0f172a 0%, #0c2d48 100%)' },
      { type: 'shape', shape: 'rect', x: 60, y: 60, width: 1080, height: 510, color: '#ffffff', opacity: 0.05, border_radius: 20 },
      { type: 'text', key: 'category', label: 'Category', default_value: 'STEP-BY-STEP GUIDE', x: 100, y: 110, font_size: 16, font_weight: '600', color: '#06b6d4' },
      { type: 'text', key: 'title', label: 'Title', default_value: 'How to Build a REST API with Node.js', x: 100, y: 180, font_size: 48, font_weight: '700', color: '#ffffff', max_width: 900 },
      { type: 'text', key: 'description', label: 'Description', default_value: 'A complete guide for beginners to intermediate developers.', x: 100, y: 370, font_size: 22, font_weight: '400', color: '#94a3b8', max_width: 900 },
      { type: 'text', key: 'author', label: 'Author', default_value: 'Author Name', x: 100, y: 490, font_size: 18, font_weight: '500', color: '#06b6d4' },
    ],
  },
  {
    name: 'Quote Card',
    slug: 'quote-card',
    category: 'social',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 5,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #0f0f23 0%, #1a1a3e 100%)' },
      { type: 'text', key: 'quote_mark', label: 'Quote Mark', default_value: '"', x: 80, y: 60, font_size: 120, font_weight: '700', color: '#8b5cf6' },
      { type: 'text', key: 'quote', label: 'Quote', default_value: 'The best way to predict the future is to create it.', x: 100, y: 180, font_size: 44, font_weight: '600', color: '#ffffff', max_width: 1000 },
      { type: 'text', key: 'author', label: 'Author', default_value: '-- Peter Drucker', x: 100, y: 460, font_size: 24, font_weight: '500', color: '#a78bfa' },
    ],
  },
  {
    name: 'Stats / Numbers',
    slug: 'stats-numbers',
    category: 'marketing',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: true,
    sort_order: 6,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #020617 0%, #0f172a 100%)' },
      { type: 'text', key: 'headline', label: 'Headline', default_value: 'OUR IMPACT IN NUMBERS', x: 80, y: 80, font_size: 20, font_weight: '600', color: '#06b6d4' },
      { type: 'text', key: 'stat1', label: 'Stat 1', default_value: '10M+', x: 100, y: 200, font_size: 72, font_weight: '800', color: '#ffffff' },
      { type: 'text', key: 'stat1_label', label: 'Stat 1 Label', default_value: 'Users worldwide', x: 100, y: 290, font_size: 20, font_weight: '400', color: '#64748b' },
      { type: 'text', key: 'stat2', label: 'Stat 2', default_value: '99.9%', x: 500, y: 200, font_size: 72, font_weight: '800', color: '#ffffff' },
      { type: 'text', key: 'stat2_label', label: 'Stat 2 Label', default_value: 'Uptime SLA', x: 500, y: 290, font_size: 20, font_weight: '400', color: '#64748b' },
      { type: 'text', key: 'stat3', label: 'Stat 3', default_value: '500K', x: 840, y: 200, font_size: 72, font_weight: '800', color: '#ffffff' },
      { type: 'text', key: 'stat3_label', label: 'Stat 3 Label', default_value: 'API calls/day', x: 840, y: 290, font_size: 20, font_weight: '400', color: '#64748b' },
      { type: 'text', key: 'brand', label: 'Brand', default_value: 'yourcompany.com', x: 100, y: 520, font_size: 22, font_weight: '500', color: '#8b5cf6' },
    ],
  },
  {
    name: 'Comparison',
    slug: 'comparison',
    category: 'marketing',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: true,
    sort_order: 7,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)' },
      { type: 'shape', shape: 'line', x: 600, y: 80, width: 2, height: 470, color: '#27272a' },
      { type: 'text', key: 'title', label: 'Title', default_value: 'Before vs After', x: 400, y: 40, font_size: 18, font_weight: '600', color: '#a1a1aa', align: 'center' },
      { type: 'text', key: 'left_title', label: 'Left Title', default_value: 'Before', x: 100, y: 120, font_size: 36, font_weight: '700', color: '#ef4444' },
      { type: 'text', key: 'left_text', label: 'Left Description', default_value: 'Manual process,\nTime consuming,\nError prone', x: 100, y: 220, font_size: 24, font_weight: '400', color: '#a1a1aa', max_width: 420 },
      { type: 'text', key: 'right_title', label: 'Right Title', default_value: 'After', x: 680, y: 120, font_size: 36, font_weight: '700', color: '#22c55e' },
      { type: 'text', key: 'right_text', label: 'Right Description', default_value: 'Automated workflow,\nInstant results,\n100% accurate', x: 680, y: 220, font_size: 24, font_weight: '400', color: '#a1a1aa', max_width: 420 },
      { type: 'text', key: 'brand', label: 'Brand', default_value: 'Powered by YourApp', x: 440, y: 560, font_size: 18, font_weight: '500', color: '#8b5cf6' },
    ],
  },
  {
    name: 'Newsletter',
    slug: 'newsletter',
    category: 'blog',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 8,
    layers: [
      { type: 'background', gradient: 'linear-gradient(180deg, #0f172a 0%, #1e293b 100%)' },
      { type: 'shape', shape: 'rect', x: 60, y: 60, width: 1080, height: 510, color: '#06b6d4', opacity: 0.05, border_radius: 24 },
      { type: 'text', key: 'issue', label: 'Issue Number', default_value: 'Issue #42', x: 120, y: 100, font_size: 18, font_weight: '600', color: '#06b6d4' },
      { type: 'text', key: 'title', label: 'Newsletter Title', default_value: 'The Weekly Dispatch', x: 120, y: 170, font_size: 52, font_weight: '800', color: '#ffffff', max_width: 960 },
      { type: 'text', key: 'highlight', label: 'Highlight', default_value: 'This week: AI breakthroughs, new frameworks, and industry trends.', x: 120, y: 310, font_size: 24, font_weight: '400', color: '#94a3b8', max_width: 900 },
      { type: 'text', key: 'subscribe', label: 'CTA', default_value: 'Subscribe free →', x: 120, y: 460, font_size: 20, font_weight: '600', color: '#06b6d4' },
    ],
  },
  {
    name: 'Testimonial',
    slug: 'testimonial',
    category: 'social',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: true,
    sort_order: 9,
    layers: [
      { type: 'background', gradient: 'linear-gradient(135deg, #0c0c1d 0%, #1a1a3e 100%)' },
      { type: 'shape', shape: 'rect', x: 60, y: 60, width: 1080, height: 510, color: '#ffffff', opacity: 0.03, border_radius: 24 },
      { type: 'text', key: 'stars', label: 'Stars', default_value: '★ ★ ★ ★ ★', x: 120, y: 100, font_size: 28, font_weight: '400', color: '#facc15' },
      { type: 'text', key: 'quote', label: 'Testimonial', default_value: '"This tool completely transformed our workflow. We went from hours of manual work to minutes."', x: 120, y: 180, font_size: 36, font_weight: '500', color: '#ffffff', max_width: 960 },
      { type: 'text', key: 'name', label: 'Name', default_value: 'Jane Smith', x: 120, y: 420, font_size: 22, font_weight: '600', color: '#ffffff' },
      { type: 'text', key: 'role', label: 'Role', default_value: 'CTO at TechCorp', x: 120, y: 460, font_size: 18, font_weight: '400', color: '#8b5cf6' },
    ],
  },
  {
    name: 'Minimal Dark',
    slug: 'minimal-dark',
    category: 'minimal',
    thumbnail_url: null,
    width: 1200,
    height: 630,
    is_premium: false,
    sort_order: 10,
    layers: [
      { type: 'background', color: '#000000' },
      { type: 'text', key: 'title', label: 'Title', default_value: 'Clean. Simple. Powerful.', x: 100, y: 220, font_size: 64, font_weight: '700', color: '#ffffff', max_width: 1000 },
      { type: 'text', key: 'subtitle', label: 'Subtitle', default_value: 'yoursite.com', x: 100, y: 400, font_size: 24, font_weight: '400', color: '#525252' },
    ],
  },
]
